### ISSUE TITLE
error msg by running $ ng server

### ISSUE THREAD

**Issue by HimmelStein** [okgreece/indigo#1]
$ ng server
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
** NG Live Development Server is running on http://localhost:4200. **

ERROR in ./src/main.ts
Module build failed: TypeError: Cannot read property 'exclude' of undefined
    at applyDefaults (/Users/tdong/git/indigo/node_modules/awesome-typescript-loader/src/instance.ts:266:72)
    at Object.ensureInstance (/Users/tdong/git/indigo/node_modules/awesome-typescript-loader/src/instance.ts:145:5)
    at compiler (/Users/tdong/git/indigo/node_modules/awesome-typescript-loader/src/index.ts:37:20)
    at Object.loader (/Users/tdong/git/indigo/node_modules/awesome-typescript-loader/src/index.ts:18:18)
 @ multi main
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks       Chunk Names
    index.html  3.12 kB       0       
webpack: bundle is now VALID.

Navigate to http://localhost:4200/indigo in the browser,
reponse: loading... all the time

**Comment by larjohn** [comment]
Shouldn't it be ng serve instead of ng server?

**Comment by HimmelStein** [comment]
should be ng serve -- typo in the message above. 
Platform: macOS Sierra Version 10.12.1

$ ng serve
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
** NG Live Development Server is running on http://localhost:4200. **
 10% building modules 5/7 modules 2 active ...ode_modules/style-loader/addStyles.js[TypeError: Cannot read property 'exclude' of undefined] 'TypeError: Cannot read property \'exclude\' of undefined\n    at applyDefaults (/Users/tdong/git/indigo/node_modules/awesome-typescript-loader/src/instance.ts:266:72)\n    at Object.ensureInstance (/Users/tdong/git/indigo/node_modules/awesome-typescript-loader/src/instance.ts:145:5)\n    at compiler (/Users/tdong/git/indigo/node_modules/awesome-typescript-loader/src/index.ts:37:20)\n    at Object.loader (/Users/tdong/git/indigo/node_modules/awesome-typescript-loader/src/index.ts:18:18)\n    at LOADER_EXECUTION (/Users/tdong/git/indigo/node_modules/loader-runner/lib/LoaderRunner.js:114:14)\n    at runSyncOrAsync (/Users/tdong/git/indigo/node_modules/loader-runner/lib/LoaderRunner.js:115:4)\n    at iterateNormalLoaders (/Users/tdong/git/indigo/node_modules/loader-runner/lib/LoaderRunner.js:224:2)\n    at iterateNormalLoaders (/Users/tdong/git/indigo/node_modules/loader-runner/lib/LoaderRunner.js:213:10)\n    at /Users/tdong/git/indigo/node_modules/loader-runner/lib/LoaderRunner.js:228:3\n    at Object.context.callback (/Users/tdong/git/indigo/node_modules/loader-runner/lib/LoaderRunner.js:106:13)\n    at Object.module.exports (/Users/tdong/git/indigo/node_modules/angular2-template-loader/index.js:32:10)\n    at LOADER_EXECUTION (/Users/tdong/git/indigo/node_modules/loader-runner/lib/LoaderRunner.js:114:14)\n    at runSyncOrAsync (/Users/tdong/git/indigo/node_modules/loader-runner/lib/LoaderRunner.js:115:4)\n    at iterateNormalLoaders (/Users/tdong/git/indigo/node_modules/loader-runner/lib/LoaderRunner.js:224:2)\n    at /Users/tdong/git/indigo/node_modules/loader-runner/lib/LoaderRunner.js:197:4\n    at Storage.finished (/Users/tdong/git/indigo/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:39:16)\n    at /Users/tdong/git/indigo/node_modules/enhanced-resolve/node_modules/graceful-fs/graceful-fs.js:78:16\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)'
1734ms building modules                 0ms add0m135ms c29ms asset16ms emittinggHash: 5aa34bdf9985a41d0c6f
Version: webpack 2.1.0-beta.25
Time: 1969ms
            Asset       Size  Chunks             Chunk Names
   main.bundle.js     244 kB    0, 2  [emitted]  main
 styles.bundle.js      29 kB    1, 2  [emitted]  styles
        inline.js    5.53 kB       2  [emitted]  inline
         main.map     297 kB    0, 2  [emitted]  main
       styles.map    36.8 kB    1, 2  [emitted]  styles
       inline.map    5.59 kB       2  [emitted]  inline
       index.html  772 bytes          [emitted]  
assets/.npmignore    0 bytes          [emitted]  

ERROR in ./src/main.ts
Module build failed: TypeError: Cannot read property 'exclude' of undefined
    at applyDefaults (/Users/tdong/git/indigo/node_modules/awesome-typescript-loader/src/instance.ts:266:72)
    at Object.ensureInstance (/Users/tdong/git/indigo/node_modules/awesome-typescript-loader/src/instance.ts:145:5)
    at compiler (/Users/tdong/git/indigo/node_modules/awesome-typescript-loader/src/index.ts:37:20)
    at Object.loader (/Users/tdong/git/indigo/node_modules/awesome-typescript-loader/src/index.ts:18:18)
 @ multi main
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks       Chunk Names
    index.html  3.12 kB       0       
webpack: bundle is now VALID.

**Comment by larjohn** [comment]
This is due to https://github.com/s-panferov/awesome-typescript-loader/issues/190

It should be resolved with bde1fa6000e399aa177219a7df7876dbdcd01891

**Comment by HimmelStein** [comment]
yes, the server is started now. thanks!
