### ISSUE TITLE
Parameter Configuration shows too much info

### ISSUE THREAD

**Issue by skarampatakis** [okgreece/indigo#15]
I believe that parameter configuration is a bit confusing. 
![image](https://cloud.githubusercontent.com/assets/2419820/26273609/d4fa9ab6-3d3b-11e7-97ae-766237f64a22.png)

What is the meaning of be able to select "is top concept in scheme" or "is in scheme" ?

Also Info bubble states that "if a dimension contains empty values it should not be selected for further analysis". How could I know that the dimension contains empty values and I should not select it?

**Comment by larjohn** [comment]
Attributes have been reduced to label and key.

You might want to check the preview of the data you send to avoid sending null values.

**Comment by skarampatakis** [comment]
> You might want to check the preview of the data you send to avoid sending null values.

Can't this be added as a validation? It would help a lot.
