### ISSUE TITLE
Meaning of Frequency chart on Descriptive statistics

### ISSUE THREAD

**Issue by skarampatakis** [okgreece/indigo#22]
http://apps.openbudgets.eu/cube/analytics/budget-athens-expenditure-2006__97b39/descriptive_statistics/facts?amounts=amount&dimensions=budgetPhase.prefLabel&json_data=http%3A%2F%2Fws307.math.auth.gr%2Frudolf%2Fpublic%2Fapi%2F3%2Fcubes%2Fbudget-athens-expenditure-2006__97b39%2Ffacts%3Fpagesize%3D300

On the above link there is a percent frequency chart. While it states being a percent frequency chart, it seems that it is something different. Shouldn't all values sum to 100%? Am I getting something wrong?

**Comment by larjohn** [comment]
If you mean the numbers on each bar, they represent how many facts were found to have this value in this dimension. They are not divided by the total count.
