### ISSUE TITLE
baseHref not included for sockjs

### ISSUE THREAD

**Issue by schmaluk** [okgreece/indigo#3]
The Browser sends a request to:
http://eis-openbudgets.iais.fraunhofer.de/sockjs-node/info?t=1489413664085

Where would I configure the basePath /indigo for this request?

The Url should include the baseHref /indigo 
from the config https://github.com/okgreece/indigo/blob/master/src/environments/environment.ts
And should look sthg like this:
http://eis-openbudgets.iais.fraunhofer.de/indigo/sockjs-node/info?t=1489413664085

Will forward for the time being /sockjs-node to Indigo via nginx.

**Comment by schmaluk** [comment]
Strange. Didnt find anything websocket-like in the source-code. But the browser calls unsuccessfully: http://eis-openbudgets.iais.fraunhofer.de/sockjs-node/888/oemldshu/websocket
Not sure how I should configure it properly.
Thanks a lot

**Comment by larjohn** [comment]
See https://github.com/angular/angular-cli/issues/1570

Can you start indigo by 

`npm start`
