### ISSUE TITLE
what is the command "ng" mean

### ISSUE THREAD

**Issue by wk0206** [okgreece/indigo#5]
After I install this indigo, the last step is run "ng serve", my system return an error with
 **"The program 'ng' is currently not installed. You can install it by typing:
apt install ng-common"**

I think this ng-common may be not the the correct one in this indigo, because after I install the "apt-get install ng-common" , and run "ng serve", it opens an text edit interface, do not start any server.

Does there has any thing changed or anyone met the same problem before?

**Comment by pwalsh** [comment]
Try `npm start` ( https://github.com/okgreece/indigo/blob/master/package.json#L6 )

`ng` is https://cli.angular.io not the `ng` from apt. Because it is installed in the local environment ( https://github.com/okgreece/indigo/blob/master/package.json#L72 ) it is not on your PATH as `ng`. `npm`'s script runner deals with that stuff and that is why it is always good to check `scripts` in `package.json` to see if the author/maintainer has set up some scripts there.

**Comment by pierorex** [comment]
`npm install` fails to install all the dependencies because `zone.js` and `typescript` are not found, thus `angular-cli` is not successfully installed, making `ng serve` fail in the end

**Comment by larjohn** [comment]
Can you report your npm and node versions? 

Otherwise, I may need to freeze dependency versions because the most recent ones are constantly failing.

**Comment by pierorex** [comment]
npm version 3.10.10 
node version v6.10.1

**Comment by wk0206** [comment]
wang@wang-Inspiron-7548:~$ npm -v
4.4.1
wang@wang-Inspiron-7548:~$ node -v
v7.6.0

**Comment by larjohn** [comment]
@wk0206 do you have the same issue with @pierorex ?

**Comment by wk0206** [comment]
I have the same issue with `zone.js `and `typescript`, even I install latest `zone.js` it still request specific version 0.7.2

**Comment by pwalsh** [comment]
Lazarus you definitely have to freeze dependencies in node as things change too quickly.

**Comment by larjohn** [comment]
So, in the latest commit I froze the dependencies, and it builds without warnings or errors for  me, locally. Is this also the case for you @wk0206 and @pierorex ?

PS: Please clone the repository from scratch.

**Comment by pierorex** [comment]
Hello @larjohn, I don't want to be super annoying but, I'm attaching the output from `npm install` so you can see the errors I get, which are the same as before: [npm-output.txt](https://github.com/okgreece/indigo/files/866628/npm-output.txt)

**Comment by larjohn** [comment]
No annoyance @pierorex , we are here just for resolving issues!

> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents): npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

Just a warning: fsevents is only relevant on Mac OS, it does not compile on Linux or Windows.

>npm WARN @angular/flex-layout@2.0.0-rc.1 requires a peer of zone.js@^0.7.2 but none was installed.
npm WARN @angular/core@2.4.10 requires a peer of zone.js@^0.7.2 but none was installed.

zone.js@0.7.8 is installed instead - it might conflict, but this is just a warning. However, I would expect that v0.7.2 is installed - see here https://github.com/okgreece/indigo/blob/cutting-edge/package.json
Maybe some other package installs v0.7.8. Anyway, it has worked for me even with versions >0.8.0.

Can you also try `npm start` and see what goes wrong?

**Comment by pierorex** [comment]
Executing `npm start` gives this:
```
@obeu/indigo@1.0.0 start /home/piero/Documents/fraunhofer/indigo
ng serve --host 0.0.0.0 

** NG Live Development Server is running on http://0.0.0.0:4200 **
Hash: e4d4eb1ff2fa6e7ecc14                                                                 
Time: 27311ms
chunk    {0} styles.bundle.js, styles.bundle.js.map (styles) 124 kB {3} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 509 kB {2} [initial] [rendered]
chunk    {2} vendor.bundle.js, vendor.bundle.js.map (vendor) 6.25 MB [initial] [rendered]
chunk    {3} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

**ERROR in /home/piero/Documents/fraunhofer/indigo/node_modules/@types/lodash/index.d.ts (19449,15): All declarations of 'WeakMap' must have identical type parameters.)**
webpack: Failed to compile.
```

**Comment by pwalsh** [comment]
on macOS with npm 3.10.8 and node 7.0.0 I need to remove the type annotations for lodash `"@types/lodash": "4.14.52"`, and drop the typescript version down to 2.1.4 to get the app to compile on `npm start`.

Related https://github.com/DefinitelyTyped/DefinitelyTyped/issues/14324

**Comment by larjohn** [comment]
@pwalsh lodash annotation are frozen at "4.14.55" in the cutting edge branch. Are we all talking about this branch?

**Comment by pwalsh** [comment]
@larjohn nope, I pulled master (did not notice that there is a cutting edge which is ahead of master).

**Comment by larjohn** [comment]
Sorry, this was probably shared in an email with the Fraunhofer guys. Does the cutting edge branch work for you in macOS?

**Comment by wk0206** [comment]
@pwalsh I got the same error as @pierorex .

It is something with WeakMap.
I am working on the Linux ubuntu system.
After I uninstall the @types/lodash@4.14.52 , I can not install version 2.1.4

will you update the package.json to put an available @types/lodash?
or otherwise I will go on search for solution to install a 2.1.4 @types/lodash.

`
root@wang-Inspiron-7548:~/OP/indigo# npm install @types/lodash@2.1.4
npm ERR! code ETARGET
npm ERR! notarget No compatible version found: @types/lodash@2.1.4
npm ERR! notarget Valid install targets:
npm ERR! notarget 4.0.14-alpha, 4.0.15-alpha, 4.0.20-alpha, 4.0.21-alpha, 4.0.22-alpha, 4.0.23-alpha, 4.0.24-alpha, 4.0.25-alpha, 4.0.26-alpha, 0.0.26-alpha, 0.0.27, 0.0.28, 0.0.29, 4.14.30, 4.14.31, 4.14.32, 4.14.33, 4.14.34, 4.14.35, 4.14.36, 4.14.37, 4.14.38, 4.14.39, 4.14.40, 4.14.41, 4.14.42, 4.14.43, 4.14.44, 4.14.45, 4.14.46, 4.14.47, 4.14.48, 3.10.0, 4.14.49, 4.14.50, 4.14.51, 4.14.52, 4.14.53, 3.10.1, 4.14.54, 4.14.55, 4.14.56, 4.14.57, 4.14.58, 4.14.59, 4.14.0-next.0, 4.14.60, 4.14.61
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
`

**Comment by wk0206** [comment]
@pwalsh I got the same compile error as @pierorex 
And follow your suggestion , downgrade the typescript to 2.1.4, then compile passed.
Wish you can repair the dependency based on this issue .
`npm uninstall typescript
npm install typescript@2.1.4`

**Comment by larjohn** [comment]
I ll check it later today with Ubuntu

Sent from my Windows 10 phone

**Comment by larjohn** [comment]
@wk0206 I checked with Ubuntu server 16.2 LTS and : 
node v7.1.0
npm v3.10.9 

and it worked out of the box. 

You might have to clear your node_modules directory or caches here and there.

**Comment by wk0206** [comment]
thank you , this issue should be closed.
