### ISSUE TITLE
Indigo integration with DAM

### ISSUE THREAD

**Issue by pierorex** [okgreece/indigo#8]
I need to use DAM for some computations and wanted to use Indigo as the frontend that builds the correct queries.

Tiansi told me that we just need to point Indigo to use this backend server: http://dam-obeu.iais.fraunhofer.de/
Though we don't know where to put that. Is this possible?

**Comment by larjohn** [comment]
Currently, Indigo only supports descriptive statistics and timeseries, which can but are not directed through DAM, as there was only the outliers case needing it. After integrating clestering, we are going to catch up with DAM to include outliers as well and port the integration of our algorithms to DAM.
